/* وسائط دقيقة معرفة: تخزين محلي في IndexedDB للديمو. */
let minutePreviewUrl,minutePlaybackUrl;
function minuteDb(){return new Promise((resolve,reject)=>{const r=indexedDB.open('basmat-media',1);r.onupgradeneeded=()=>r.result.createObjectStore('files');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function minuteFile(action,id,value){const db=await minuteDb();try{return await new Promise((resolve,reject)=>{const tx=db.transaction('files',action==='get'?'readonly':'readwrite'),store=tx.objectStore('files');let result;const r=action==='put'?store.put(value,id):action==='delete'?store.delete(id):store.get(id);r.onsuccess=()=>result=r.result;tx.oncomplete=()=>resolve(result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('تعذر الحفظ'));});}finally{db.close();}}
function minuteList(){return Array.isArray(state.minutes)?state.minutes:[];}
function minuteCanView(m){return m&&(m.status==='published'||state.role==='reviewer'||(state.role==='employee'&&m.ownerId===state.employeeId));}
const originalMinuteBrowse=minuteBrowseContent;
minuteBrowseContent=function(){const list=minuteList().filter(minuteCanView);return `${list.length?`<div class="section-title"><h2>الدقائق المرفوعة</h2></div><div class="grid grid-3">${list.map(m=>`<div class="card"><div class="video-thumb"><div class="video-art"></div><button class="play" onclick="go('minute-player','${m.id}')">▶</button></div><h3>${escapeKnowledge(m.title)}</h3><p class="meta">${escapeKnowledge(m.owner)} · ${escapeKnowledge(m.dept)}</p><span class="status ${m.status}">${statusText(m.status)}</span><p>${escapeKnowledge(m.summary)}</p><button class="btn btn-gold w100" onclick="go('minute-player','${m.id}')">${m.type==='audio'?'استماع':'مشاهدة'}</button></div>`).join('')}</div>`:''}${originalMinuteBrowse()}`;};
minuteRecordContent=function(){return `<p class="minute-intro">ارفع فيديو أو مقطعًا صوتيًا، وعاينه ثم أرسله للمراجعة.</p><form class="card minute-form" onsubmit="submitMinute(event)"><div class="minute-fields"><label>عنوان الدقيقة *<input id="minuteTitle" class="input" maxlength="160" required></label><label>اسم المتحدث<input class="input" value="${escapeKnowledge(cu().name)}" readonly></label></div><label>ملخص قصير *<textarea id="minuteSummary" class="input" maxlength="2000" rows="4" required></textarea></label><fieldset class="minute-kind"><legend>نوع المحتوى</legend><label><input type="radio" name="minuteType" value="video" checked onchange="minuteChangeType()"> فيديو</label><label><input type="radio" name="minuteType" value="audio" onchange="minuteChangeType()"> صوت</label></fieldset><label class="upload-box"><b>اختيار ملف</b><small>فيديو MP4 أو مقطع صوتي — حتى ٥٠ ميجابايت</small><input id="minuteFile" type="file" accept="video/mp4,video/webm,audio/*" required onchange="minutePreview()"></label><div id="minutePreview" style="margin-top:18px"></div><div class="minute-submit"><button id="minuteSubmit" class="btn btn-gold">إرسال للمراجعة</button></div></form>`;};
function minuteChangeType(){const input=document.getElementById('minuteFile');input.value='';input.accept=document.querySelector('[name=minuteType]:checked').value==='audio'?'audio/*':'video/mp4,video/webm';minutePreview();}
function minuteValidate(file,type){if(!file)return 'اختاري ملفًا أولًا';if(!file.size)return 'الملف فارغ';if(file.size>50*1024*1024)return 'حجم الملف يتجاوز ٥٠ ميجابايت';const kind=file.type||( /\.mp4$/i.test(file.name)?'video/mp4':/\.webm$/i.test(file.name)?'video/webm':'');if(!kind.startsWith(type+'/'))return 'نوع الملف لا يطابق نوع المحتوى المحدد';return '';}
function minutePreview(){if(minutePreviewUrl)URL.revokeObjectURL(minutePreviewUrl);minutePreviewUrl=null;const file=document.getElementById('minuteFile').files[0],box=document.getElementById('minutePreview');box.innerHTML='';if(!file)return;const type=document.querySelector('[name=minuteType]:checked').value,error=minuteValidate(file,type);if(error){notify(error);return;}minutePreviewUrl=URL.createObjectURL(file);box.innerHTML=`<${type} controls playsinline style="width:100%;max-height:440px" src="${minutePreviewUrl}"></${type}><p class="meta">${escapeKnowledge(file.name)}</p>`;}
submitMinute=async function(e){e.preventDefault();if(!['employee','reviewer'].includes(state.role)){notify('إرسال الدقيقة متاح للموظف');return;}const title=document.getElementById('minuteTitle').value.trim(),summary=document.getElementById('minuteSummary').value.trim(),file=document.getElementById('minuteFile').files[0],type=document.querySelector('[name=minuteType]:checked').value,error=minuteValidate(file,type);if(error||!title||!summary){notify(error||'أكملي العنوان والملخص');return;}const button=document.getElementById('minuteSubmit');if(button.disabled)return;button.disabled=true;button.textContent='جارٍ الحفظ…';const ownerId=currentPersonId(),owner=cu().name,dept=cu().dept,id='minute-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8);let added=false;try{await minuteFile('put',id,file);if(!Array.isArray(state.minutes))state.minutes=[];state.minutes.unshift({id,title,summary,type,ownerId,owner,dept,status:'review',date:new Date().toISOString().slice(0,10),filename:file.name});added=true;save();showModal('تم إرسال دقيقتك للمراجعة','تم حفظ المقطع، ويمكنك مشاهدته الآن. يظهر لبقية الموظفين بعد اعتماد المراجع.',`<button class="btn btn-primary w100" onclick="closeModal();go('minute-player','${id}')">مشاهدة المقطع</button>`);}catch(err){if(added)state.minutes=state.minutes.filter(m=>m.id!==id);try{await minuteFile('delete',id);}catch{}console.error(err);notify('تعذر حفظ المقطع في المتصفح. جرّبي ملفًا أصغر وتأكدي من توفر مساحة.');}finally{button.disabled=false;button.textContent='إرسال للمراجعة';}};
function minutePlayer(){const m=minuteList().find(x=>x.id===state.current);if(!minuteCanView(m))return shell('<p>المقطع غير متاح.</p>');return shell(`${crumb('دقيقة معرفة ← مشاهدة المقطع')}<button class="btn btn-soft" onclick="go('${state.role==='reviewer'?'reviewer-home':'minute'}')">العودة إلى القائمة</button><div class="card" style="margin-top:20px"><h1>${escapeKnowledge(m.title)}</h1><p class="meta">${escapeKnowledge(m.owner)} · ${escapeKnowledge(m.dept)}</p><span class="status ${m.status}">${statusText(m.status)}</span><div id="minutePlayerMedia" style="margin-top:20px">جارٍ تحميل المقطع…</div><p>${escapeKnowledge(m.summary)}</p>${state.role==='reviewer'&&m.status==='review'?`<button class="btn btn-primary" onclick="publishMinute('${m.id}')">اعتماد ونشر ✓</button>`:''}</div>`);}
async function hydrateMinutePlayer(){if(minutePlaybackUrl){URL.revokeObjectURL(minutePlaybackUrl);minutePlaybackUrl=null;}const box=document.getElementById('minutePlayerMedia');if(!box)return;const id=state.current,m=minuteList().find(x=>x.id===id);if(!minuteCanView(m))return;try{const file=await minuteFile('get',id);if(!box.isConnected||state.current!==id)return;if(!file){box.textContent='الملف غير موجود في هذا المتصفح. ارفعيه من جديد.';return;}minutePlaybackUrl=URL.createObjectURL(file);box.innerHTML=`<${m.type} id="minuteActualPlayer" controls playsinline preload="metadata" style="width:100%;max-height:600px" src="${minutePlaybackUrl}"></${m.type}>`;document.getElementById('minuteActualPlayer').onerror=()=>notify('تعذر تشغيل صيغة المقطع؛ استخدمي فيديو MP4 بترميز H.264');}catch{box.textContent='تعذر قراءة المقطع المحفوظ.';}}
function publishMinute(id){if(state.role!=='reviewer')return;const m=minuteList().find(x=>x.id===id);if(!m||m.status!=='review'||m.dept!==cu().dept)return;m.status='published';try{save();render();showModal('تم اعتماد ونشر الدقيقة','أصبح المقطع متاحًا للموظفين.',`<button class="btn btn-primary w100" onclick="closeModal();go('reviewer-home')">العودة إلى القائمة</button>`);}catch{m.status='review';notify('تعذر حفظ النشر');}}
const originalMinuteReviewerHome=reviewerHome;
reviewerHome=function(){const section=`<section class="card" style="margin:20px 0"><h2>مراجعة دقيقة معرفة</h2>${minuteList().filter(m=>m.status==='review'&&m.dept===cu().dept).map(m=>`<div class="review-item"><h3>${escapeKnowledge(m.title)}</h3><p>${escapeKnowledge(m.owner)} · ${escapeKnowledge(m.dept)}</p><button class="btn btn-primary" onclick="go('minute-player','${m.id}')">مشاهدة ومراجعة</button></div>`).join('')||'<p class="meta">لا توجد دقائق تحتاج إلى المراجعة.</p>'}</section>`;return originalMinuteReviewerHome().replace('<div id="reviewList"',section+'<div id="reviewList"');};
const originalMinuteRender=render;
render=function(){if(minutePreviewUrl){URL.revokeObjectURL(minutePreviewUrl);minutePreviewUrl=null;}if(state.route==='minute-player'){app.innerHTML=minutePlayer();}else originalMinuteRender();hydrateMinutePlayer();};
